global:
  scrape_interval: 10s
  #evaluation_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]


  - job_name: 'wetter-metrics'
    metrics_path: /api/metrics
    static_configs:
      #- targets: ['localhost:5001']
      - targets: ['host.docker.internal:5001']
        labels:
          instance: 'wetter'
          job: 'wetter-data'

  - job_name: 'wetter-metrics2'
    metrics_path: /api/metrics
    static_configs:
      #- targets: ['localhost:5001']
      - targets: ["localhost:5001"]
        labels:
          instance: 'wetter'
          job: 'wetter-data'        

  - job_name: 'wetter-metrics3'
    metrics_path: /api/metrics
    static_configs:
      #- targets: ['localhost:5001']
      - targets: ["192.168.2.1:5001"]
        labels:
          instance: 'wetter'
          job: 'wetter-data' 