name: Node.js CI/CD with Docker

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
    
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: create env file
      run: |
        touch .env
        echo OPEN_WEATHER_API=${{ secrets.WETTER_KEY }} >> .env
        echo NREL_PVWATT_KEY=${{ secrets.STROM_KEY }} >> .env
        echo PREISE_API_KEY=${{ secrets.PREIS_KEY }} >> .env

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18       
        
    - name: Install dependencies
      run: npm install

    - name: Setup Node.js
      run: node mailer.js 
      
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/prosumer_app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/prosumer_app:latest
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "63.35.124.143,54.72.255.250" # i can also put all host in one variable separated by comma
        port: 22    
        username: ec2-user
        key: ${{ secrets.PRIV_KEY }}
        script: |
             sudo docker-compose pull prosumerapp
             sudo docker-compose up -d prosumerapp # restart the service
            #sudo docker restart prosumer 
            #sudo docker-compose up -d
